### ISSUE TITLE
Page urls are wrong

### ISSUE THREAD

**Issue by andreamangano** [lmammino/loige.co#34]
Hi Luciano,
I report you a bug that I found browsing your amazing website

The page URLs listed in https://loige.co/sitemap.xml are wrong because the `/` separator between the domain and the page path is missing.

For example, the page url `https://loige.co/middy-1-is-here/` is badly generated as `https://loige.comiddy-1-is-here/`

https://github.com/lmammino/loige.co/blob/1fe9ec07818123f103bdc19418ded7494bc526e1/gatsby-sitemap.js#L36

Bye

**Comment by lmammino** [comment]
Thanks for spotting this. I noticed there's a similar issue in the RSS feed as well! 😓 

Submitting a fix shortly!
